# Network interface variable key in the environment
ETHERNET_INTERFACE_KEY = 'ETHERNET_INTERFACE'
ETHERNET_CONNECTION_KEY = 'ETHERNET_CONNECTION_NAME'
WIRELESS_CONNECTION_NAME_KEY = 'WIRELESS_CONNECTION_NAME'
MODE_FILE_PATH = 'MODE_FILE_PATH'

# Command to get IP and mask
IP_COMMAND_TEMPLATE = "ip addr show dev {}"

